### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mkalinov** [sonomapartners/web-resources-with-react#1]
Hi Corey,

The compilation throws the follow error for webpack --progress

1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info prebuild demo@1.0.0
7 info build demo@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info demo@1.0.0 Failed to exec build script
10 verbose stack Error: demo@1.0.0 build: `webpack --progress`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid demo@1.0.0
12 verbose cwd C:\Users\michaelk.EMPOWER\Downloads\web-resources-with-react-master\web-resources-with-react-master
13 error Windows_NT 6.3.9600
14 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error demo@1.0.0 build: `webpack --progress`
18 error Exit status 1
19 error Failed at the demo@1.0.0 build script 'webpack --progress'.
19 error This is most likely a problem with the demo package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     webpack --progress
19 error You can get their info via:
19 error     npm owner ls demo
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by csobrien** [comment]
I just did a fresh clone from here, followed by an `npm install` and `npm run build` and it worked.  I'm using node v4.4.6 and npm v2.15.5.  Maybe try a newer version of node?

**Comment by mkalinov** [comment]
I believe 4.4.6 is not a version but build. cmd: note -v   shows the version
I have node  4.4.7 LS, v0.12.2 and npm v2.7.4
According to [npm site](https://www.npmjs.com/) npm version (cmd: npm -v) suppose to be higher than 2.1.8, node > v0.10.32.
Could you please check?

**Comment by csobrien** [comment]
Yeah that is what I used to check the version previously.  I just ran this again from a command prompt:

```
C:\Users\cobrien>node -v
v4.4.6

C:\Users\cobrien>npm -v
2.15.5
```
